server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true
management.security.enabled: false
endpoints.health.sensitive: false

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException